apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:jfOkI09B7OkNBzWyqPMMAHl/PIs7b+5gyRMQXGbx9xRc1N2lrz7IrR5eCd+AgvRpKmFBMuws/ksRnp3YLppB0FIkDc5aeQJF5wxU0N8GrkQ0R4VixLCmGA14DhedzpkZa7bX+SoA1gYA7tRyEX1McUT42sOu0fiFN1Y2Sm0NHuZ8FYBm30dk7si5hk6hd4pdWSr+bJJ4EuavjC8TS6Vsx0cdmJzHpdyzD2+zeFGs42NuIoXx+dSf7jWtllIzTJ5fE7XR+SU8CLNqXxEUAuSPMP1CwY6kBrlXQ9QsF3Sxiyt1hqYSAUuyZYQthLo=,iv:vweRjpn2S951Mlq0pmjx8WGSkp3h9YpOhQk6mKBH0Ho=,tag:Z84Hn5la/bDmMm6iJjhzNQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age154xpy2m5cctdw99q5xtpgw3u4tvx7txym2ct36pacedmrc7suaeqxsr4th
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TkJoR2Z4ZmVRQjJKT0R1
            d00zdVNTWVhXVW9ESmpZcHBwL2cvcGE0VlRBCjNuV3p4RW43a1k3K2JPNnE3V05B
            QTVhalJ0Y2NwU1pXeVlRUEtzWnAvZ0EKLS0tIHBGR0JRMkZXeXhFUGxIQXhuYjBs
            eDRkTERhZlF3UHFMOEFhenNFVGxYRlkKH/NuOGzVeYi9PyL8ePI6YliJB27Ip/cc
            u01E1ttypZZWPjCby6YNpaIm1cIsv5qLxtDmfSygyDUzgcRocN+1BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T18:47:42Z"
    mac: ENC[AES256_GCM,data:fsOOcsgnmc+mZUaA+UXqOnCCMotCAqx5Z3UHqi6BT5xaK21+Uh/2sw8Y8gNo2CsfWDmVJ4lKzyumYBigd9oAyd5q0+3WqpXMy8Aj27YZb4sfJ2rywEkVCq8IlIJWUoSvnmuqNYsZsD8+NrlR5ZB3P9gKgTpRJ1tpVgL61sg93ZI=,iv:DdV5sAKoISlXurE2ZOVhWhBJIq1YCsqFS6Mdzn/nzOg=,tag:XOdUMYMkqnmRzDmwFeeptg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
